-- ==========================================
-- ENTERPRISE IDP DATABASE SCHEMA
-- Features: Global Identity, Tenant Isolation, RBAC & SuperAdmin Control
-- ==========================================

-- Enable UUID generation support in PostgreSQL
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. ENUMS & DOMAIN TYPES
-- ==========================================
DO $$ BEGIN
    CREATE TYPE user_status AS ENUM ('UNVERIFIED', 'PENDING', 'ACTIVE', 'SUSPENDED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE invite_status AS ENUM ('PENDING', 'ACCEPTED', 'EXPIRED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE tenant_status AS ENUM ('PENDING_APPROVAL', 'ACTIVE', 'FROZEN', 'DELETED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- ==========================================
-- 2. CORE PLATFORM ARCHITECTURE
-- ==========================================

-- TENANTS: Isolated Corporate Workspaces
CREATE TABLE IF NOT EXISTS tenants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  status tenant_status DEFAULT 'ACTIVE' NOT NULL, -- SuperAdmin kill switch control
  company_name VARCHAR(255) NOT NULL,
  custom_domain VARCHAR(255) UNIQUE, 
  logo_url TEXT,                      
  theme_color VARCHAR(50) DEFAULT '#000000',
  
  -- Compliance & Identity
  legal_name VARCHAR(255),
  tax_id VARCHAR(100),
  registration_number VARCHAR(100),
  industry VARCHAR(100),
  org_size VARCHAR(50),
  
  -- Address Info
  address_street TEXT,
  address_city VARCHAR(100),
  address_state VARCHAR(100),
  address_pincode VARCHAR(20),

  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- USERS: Global Identity Matrix
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Global Uniqueness Coordinates
  email VARCHAR(255) NOT NULL UNIQUE,
  mobile_no VARCHAR(20) NOT NULL UNIQUE,
  
  -- Name Split
  first_name VARCHAR(100) NOT NULL,
  middle_name VARCHAR(100),
  last_name VARCHAR(100) NOT NULL,
  
  -- Profile Details
  gender VARCHAR(20) NOT NULL,
  country_code VARCHAR(10) NOT NULL DEFAULT '91',
  date_of_birth DATE NOT NULL,
  alternate_email VARCHAR(255),
  mother_tongue VARCHAR(100) NOT NULL,
  
  -- Security Questions
  security_question_1 VARCHAR(255) NOT NULL,
  security_answer_1 VARCHAR(255) NOT NULL,
  security_question_2 VARCHAR(255) NOT NULL,
  security_answer_2 VARCHAR(255) NOT NULL,

  password_hash TEXT NOT NULL, 

  -- Global Platform Flags
  is_superadmin BOOLEAN DEFAULT FALSE NOT NULL,
  is_blacklisted BOOLEAN DEFAULT FALSE NOT NULL,
  
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- WORKSPACE MEMBERSHIPS: Mapping Global Users to Isolated Tenants
CREATE TABLE IF NOT EXISTS workspace_memberships (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  status user_status DEFAULT 'UNVERIFIED' NOT NULL,
  is_tenant_admin BOOLEAN DEFAULT FALSE NOT NULL,
  joined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  
  PRIMARY KEY (user_id, tenant_id)
);

-- ==========================================
-- 3. METERING & BILLING ENGINE
-- ==========================================
CREATE TABLE IF NOT EXISTS tenant_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  
  -- Billing Tier Information
  plan_tier VARCHAR(50) DEFAULT 'FREE_TIER' NOT NULL, 
  
  -- The current billing window
  current_cycle_start TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  current_cycle_end TIMESTAMPTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '1 month'),
  
  -- Live Metering Counters
  mau_count INT DEFAULT 0 NOT NULL,         
  api_request_count BIGINT DEFAULT 0 NOT NULL, 
  
  -- Configurable Quotas (Null means unlimited)
  max_mau INT DEFAULT 100, 
  max_api_requests BIGINT DEFAULT 10000,
  
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  
  UNIQUE(tenant_id)
);

-- ==========================================
-- 4. TOKEN LIFECYCLE MANAGEMENT
-- ==========================================
-- Secure Refresh Tokens for session rotations
CREATE TABLE IF NOT EXISTS refresh_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  token_hash VARCHAR(255) NOT NULL UNIQUE, 
  is_revoked BOOLEAN DEFAULT FALSE NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Short-lived, secure invite links generated by HR
CREATE TABLE IF NOT EXISTS invitations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL,
  token_hash VARCHAR(255) NOT NULL UNIQUE, 
  invited_by UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
  status invite_status DEFAULT 'PENDING' NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==========================================
-- 5. ACCESS CONTROL (Modules & RBAC)
-- ==========================================
-- Apps / Modules registered inside the tenant
CREATE TABLE IF NOT EXISTS modules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  
  UNIQUE(tenant_id, name)
);

-- Custom Roles defined by HR 
CREATE TABLE IF NOT EXISTS roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  
  UNIQUE(tenant_id, name)
);

-- Granular permissions 
CREATE TABLE IF NOT EXISTS permissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL, 
  resource VARCHAR(255) NOT NULL, 
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  
  UNIQUE(tenant_id, name, resource)
);

-- ==========================================
-- 6. JUNCTION TABLES (Mappings)
-- ==========================================
CREATE TABLE IF NOT EXISTS role_permissions (
  role_id UUID REFERENCES roles(id) ON DELETE CASCADE NOT NULL,
  permission_id UUID REFERENCES permissions(id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  role_id UUID REFERENCES roles(id) ON DELETE CASCADE NOT NULL,
  assigned_by UUID REFERENCES users(id) ON DELETE SET NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS user_modules (
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  module_id UUID REFERENCES modules(id) ON DELETE CASCADE NOT NULL,
  assigned_by UUID REFERENCES users(id) ON DELETE SET NULL,
  assigned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  access_level VARCHAR(10) DEFAULT 'READ',
  PRIMARY KEY (user_id, module_id)
);

-- ==========================================
-- 7. PLATFORM SECURITY & AUDIT
-- ==========================================
-- Platform Threat Intelligence (Global IP Ban Matrix)
CREATE TABLE IF NOT EXISTS platform_ip_bans (
  ip_address VARCHAR(45) PRIMARY KEY, 
  reason TEXT NOT NULL,               
  banned_by UUID REFERENCES users(id) ON DELETE SET NULL, 
  expires_at TIMESTAMPTZ,             
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Workspace Audit Ledger
CREATE TABLE IF NOT EXISTS audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE SET NULL,
  actor_id UUID REFERENCES users(id) ON DELETE SET NULL,
  event_type VARCHAR(100) NOT NULL,     
  ip_address VARCHAR(45),
  user_agent TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb, 
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- SuperAdmin Control Plane Ledger
CREATE TABLE IF NOT EXISTS superadmin_audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id UUID REFERENCES users(id) ON DELETE SET NULL, 
  target_tenant_id UUID REFERENCES tenants(id) ON DELETE SET NULL, 
  target_user_id UUID REFERENCES users(id) ON DELETE SET NULL,     
  action VARCHAR(100) NOT NULL, 
  ip_address VARCHAR(45),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==========================================
-- 8. OPTIMIZATION INDEXES
-- ==========================================
-- Foreign key and join performance indexes
CREATE INDEX IF NOT EXISTS idx_workspace_memberships_tenant ON workspace_memberships(tenant_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON refresh_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_invitations_hash ON invitations(token_hash);
CREATE INDEX IF NOT EXISTS idx_modules_tenant ON modules(tenant_id);
CREATE INDEX IF NOT EXISTS idx_roles_tenant ON roles(tenant_id);
CREATE INDEX IF NOT EXISTS idx_permissions_tenant ON permissions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_tenant ON audit_logs(tenant_id);

-- SuperAdmin Access and Security lookup indexes
CREATE INDEX IF NOT EXISTS idx_users_superadmin ON users(is_superadmin) WHERE is_superadmin = TRUE;
CREATE INDEX IF NOT EXISTS idx_users_blacklisted ON users(is_blacklisted) WHERE is_blacklisted = TRUE;
CREATE INDEX IF NOT EXISTS idx_tenant_subscriptions_tenant ON tenant_subscriptions(tenant_id);