-- Enable UUID generation support in PostgreSQL
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. ENUMS & DOMAIN TYPES
-- ==========================================
DO $$ BEGIN
    CREATE TYPE user_status AS ENUM ('UNVERIFIED', 'PENDING', 'ACTIVE', 'SUSPENDED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE invite_status AS ENUM ('PENDING', 'ACCEPTED', 'EXPIRED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- ==========================================
-- 2. CORE TENANT & BRANDING
-- ==========================================
CREATE TABLE IF NOT EXISTS tenants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_name VARCHAR(255) NOT NULL,
  custom_domain VARCHAR(255) UNIQUE, 
  logo_url TEXT,                      
  theme_color VARCHAR(50) DEFAULT '#000000',
  
  -- Compliance & Identity
  legal_name VARCHAR(255),
  tax_id VARCHAR(100),
  registration_number VARCHAR(100),
  industry VARCHAR(100),
  org_size VARCHAR(50),
  
  -- Address Info
  address_street TEXT,
  address_city VARCHAR(100),
  address_state VARCHAR(100),
  address_pincode VARCHAR(20),

  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==========================================
-- 3. USERS (Multi-Tenant Scoped)
-- ==========================================
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL,
  
  -- Name Split
  first_name VARCHAR(100) NOT NULL,
  middle_name VARCHAR(100),
  last_name VARCHAR(100) NOT NULL,
  
  -- Profile Details
  gender VARCHAR(20) NOT NULL, -- 'Male', 'Female', etc.
  country_code VARCHAR(10) NOT NULL DEFAULT '91',
  mobile_no VARCHAR(20) NOT NULL,
  date_of_birth DATE NOT NULL,
  alternate_email VARCHAR(255),
  mother_tongue VARCHAR(100) NOT NULL,
  
  -- Security Questions
  security_question_1 VARCHAR(255) NOT NULL,
  security_answer_1 VARCHAR(255) NOT NULL, -- hashed in production, but we can store plaintext/hashed for now
  security_question_2 VARCHAR(255) NOT NULL,
  security_answer_2 VARCHAR(255) NOT NULL,

  password_hash TEXT NOT NULL, -- Argon2id secure hash
  status user_status DEFAULT 'UNVERIFIED' NOT NULL,
  is_tenant_admin BOOLEAN DEFAULT FALSE NOT NULL,
  
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  
  UNIQUE(tenant_id, email),
  UNIQUE(tenant_id, mobile_no)
);

-- ==========================================
-- 4. TOKEN LIFECYCLE MANAGEMENT
-- ==========================================
-- Secure Refresh Tokens for session rotations
CREATE TABLE IF NOT EXISTS refresh_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  token_hash VARCHAR(255) NOT NULL UNIQUE, -- SHA-256 hash of the refresh token
  is_revoked BOOLEAN DEFAULT FALSE NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Short-lived, secure invite links generated by HR
CREATE TABLE IF NOT EXISTS invitations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  email VARCHAR(255) NOT NULL,
  token_hash VARCHAR(255) NOT NULL UNIQUE, -- SHA-256 hash of the invite token
  invited_by UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
  status invite_status DEFAULT 'PENDING' NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==========================================
-- 5. ACCESS CONTROL (Modules & RBAC)
-- ==========================================
-- Apps / Modules registered inside the tenant
CREATE TABLE IF NOT EXISTS modules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  
  UNIQUE(tenant_id, name)
);

-- Custom Roles defined by HR (e.g., 'HR Manager', 'Payroll Analyst')
CREATE TABLE IF NOT EXISTS roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  
  UNIQUE(tenant_id, name)
);

-- Granular permissions (e.g., 'payroll:read', 'leave:approve')
CREATE TABLE IF NOT EXISTS permissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL, -- e.g., "read", "write", "delete"
  resource VARCHAR(255) NOT NULL, -- e.g., "payroll", "documents"
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  
  UNIQUE(tenant_id, name, resource)
);

-- ==========================================
-- 6. JUNCTION TABLES (Mappings)
-- ==========================================
-- Map Roles to Permissions
CREATE TABLE IF NOT EXISTS role_permissions (
  role_id UUID REFERENCES roles(id) ON DELETE CASCADE NOT NULL,
  permission_id UUID REFERENCES permissions(id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (role_id, permission_id)
);

-- Map Users to Roles
CREATE TABLE IF NOT EXISTS user_roles (
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  role_id UUID REFERENCES roles(id) ON DELETE CASCADE NOT NULL,
  assigned_by UUID REFERENCES users(id) ON DELETE SET NULL,
  PRIMARY KEY (user_id, role_id)
);

-- Map Users to Allowed Modules (for user landing routing)
CREATE TABLE IF NOT EXISTS user_modules (
  user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  module_id UUID REFERENCES modules(id) ON DELETE CASCADE NOT NULL,
  assigned_by UUID REFERENCES users(id) ON DELETE SET NULL,
  assigned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  access_level VARCHAR(10) DEFAULT 'READ',
  PRIMARY KEY (user_id, module_id)
);

-- ==========================================
-- 7. COMPLIANCE & MONITORING
-- ==========================================
CREATE TABLE IF NOT EXISTS audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES tenants(id) ON DELETE SET NULL,
  actor_id UUID REFERENCES users(id) ON DELETE SET NULL,
  event_type VARCHAR(100) NOT NULL,     -- e.g., 'USER_INVITED', 'ACCESS_GRANTED'
  ip_address VARCHAR(45),
  user_agent TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb, -- Store custom context details
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==========================================
-- 8. OPTIMIZATION INDEXES
-- ==========================================
-- Indexes on all foreign keys to make raw SQL JOINs ultra-fast
CREATE INDEX IF NOT EXISTS idx_users_tenant ON users(tenant_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON refresh_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_invitations_hash ON invitations(token_hash);
CREATE INDEX IF NOT EXISTS idx_modules_tenant ON modules(tenant_id);
CREATE INDEX IF NOT EXISTS idx_roles_tenant ON roles(tenant_id);
CREATE INDEX IF NOT EXISTS idx_permissions_tenant ON permissions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_tenant ON audit_logs(tenant_id);